// Reading destinations and guide notes are kept separate from the passage index.
export const workReadingLinks = {
  "birth-of-tragedy": {
    dates: "1872; new self-criticism added in 1886",
    overview: "Nietzsche asks how Greek tragedy could confront suffering without concluding that existence should be rejected. Apollo and Dionysus name artistic forces whose relation structures his answer. The book also makes a historically situated case for Wagner, so its claims about Greece and its hopes for modern culture need to be examined separately.",
    start: ["Read §§1–4 for the relation between Apollonian form and Dionysian experience.", "Read §§7–8 for the chorus, then §§21–25 for tragedy and aesthetic affirmation.", "Return to the 1886 ‘Attempt at Self-Criticism’ and ask which commitments Nietzsche now rejects."],
    question: "Does the book explain how art makes suffering bearable, or does it require a metaphysical consolation that the later Nietzsche would question?",
    edition: "Prefer Walter Kaufmann’s translation where available. The free William A. Haussmann version includes the later self-criticism; keep its 1886 date distinct from the 1872 main text.",
    links: [{ label: "Read The Birth of Tragedy", translator: "William A. Haussmann", url: "https://www.gutenberg.org/cache/epub/51356/pg51356-images.html" }],
  },
  "untimely-meditations": {
    dates: "Four essays, 1873–1876",
    overview: "These essays ask what culture, education, and historical knowledge should do for a life. Nietzsche uses contemporary figures as occasions for assessing the purposes of learning and the formation of exceptional people. Read each meditation as a sustained intervention with its own target, rather than as one continuous treatise.",
    start: ["Begin with the second meditation, ‘On the Uses and Disadvantages of History for Life,’ Preface and §§1–3.", "Compare the third meditation, ‘Schopenhauer as Educator,’ §§1–3, on education and exemplars.", "Read the essays on David Strauss and Richard Wagner with attention to their contemporary cultural targets."],
    question: "When does historical knowledge strengthen action, and when does the demand that knowledge serve life threaten honest inquiry?",
    edition: "R. J. Hollingdale’s complete translation is a useful modern edition. The free collection is titled Thoughts out of Season. Its two volumes group the four essays differently from their chronological order.",
    links: [
      { label: "Read the history and Schopenhauer essays", translator: "Adrian Collins; Thoughts out of Season, Part II", url: "https://www.gutenberg.org/files/38226/38226-h/38226-h.htm" },
      { label: "Read the Strauss and Wagner essays", translator: "Anthony M. Ludovici; Thoughts out of Season, Part I", url: "https://www.gutenberg.org/cache/epub/51710/pg51710-images.html" },
    ],
  },
  "human-all-too-human": {
    dates: "Volume I: 1878; supplements: 1879–1880; new prefaces: 1886",
    overview: "The free spirit investigates beliefs that once seemed elevated or self-evident by looking for their human origins. Short observations about morality, religion, art, and social life replace the earlier book’s large account of tragic culture. The aphoristic form asks readers to compare cases and test explanations without assuming that every section delivers a final doctrine.",
    start: ["Read Volume I §§1–3 for the turn toward historical explanation.", "Read Volume I §§35–45 for the investigation of moral feelings and competing histories of value.", "Compare an account of art in Volume I with The Birth of Tragedy, then revisit the 1886 preface as a later interpretation of the break."],
    question: "Does explaining a belief’s human origin undermine its validity, or is another argument needed?",
    edition: "Use R. J. Hollingdale’s complete two-volume translation for the modern reading preference. The free links distinguish Helen Zimmern’s Volume I from Paul V. Cohn’s Volume II; neither is a Kaufmann translation.",
    links: [
      { label: "Read Volume I", translator: "Helen Zimmern", url: "https://www.gutenberg.org/files/51935/51935-h/51935-h.htm" },
      { label: "Read Volume II", translator: "Paul V. Cohn", url: "https://www.gutenberg.org/files/37841/37841-h/37841-h.html" },
    ],
  },
  daybreak: {
    dates: "1881; new preface: 1886",
    overview: "Daybreak examines how custom, fear, habit, and interpretations of motivation acquire moral authority. Its many small investigations prepare the later genealogical project while resisting an easy replacement moral system. Attend to how often Nietzsche offers rival explanations of the same conduct.",
    start: ["Begin with §§1–9, ending with the account of the morality of custom.", "Read §§109 and 119 on drives and self-interpretation.", "Compare §9 with Genealogy, Preface §6: distinguish explaining moral authority from evaluating moral values."],
    question: "If our knowledge of our own motives is unreliable, what follows for moral judgment—and what does not follow?",
    edition: "R. J. Hollingdale provides a modern complete translation. The free J. M. Kennedy translation uses the title The Dawn of Day. Its later preface should not be dated to the original edition.",
    links: [{ label: "Read The Dawn of Day", translator: "J. M. Kennedy", url: "https://www.gutenberg.org/files/39955/39955-h/39955-h.html" }],
  },
  "gay-science": {
    dates: "Books I–IV: 1882; new preface and Book V: 1887",
    overview: "Experiments in knowledge, art, self-formation, and affirmation share this book with the unsettling announcement of the death of God. Cheerfulness here is an intellectual problem, not a guarantee that the problems of belief have been solved. The expanded edition revisits the earlier material from Nietzsche’s later perspective.",
    start: ["Read §125 alongside §343, keeping their different publication dates in view.", "Read §§276 and 341 for love of fate and the challenge of recurrence.", "Read §§344 and 374 to examine the value of truth and the possibility of multiple interpretations."],
    question: "How could intellectual honesty unsettle inherited values while also supplying a reason to continue inquiry?",
    edition: "Prefer Walter Kaufmann’s The Gay Science. The free Thomas Common translation is titled The Joyful Wisdom; it includes Book V. §§343–383 belong to the 1887 expansion.",
    links: [{ label: "Read The Joyful Wisdom", translator: "Thomas Common", url: "https://www.gutenberg.org/files/52881/52881-h/52881-h.htm" }],
  },
  zarathustra: {
    dates: "1883–1885; Part IV privately printed in 1885",
    overview: "A teacher’s speeches unfold inside a story of failed communication, departures, encounters, and transformations. The overman, self-overcoming, and recurrence must be read through this dramatic structure. Ask what a speech attempts to accomplish, how its listeners respond, and whether Zarathustra himself has yet understood what he teaches.",
    start: ["Read the Prologue §§1–5 and Part I, ‘On the Three Metamorphoses.’", "Read Part II, ‘On Self-Overcoming’ and ‘On Redemption.’", "Read Part III, ‘On the Vision and the Riddle’ and ‘The Convalescent,’ comparing their scenes with The Gay Science §341."],
    question: "Where does the drama expose a difficulty in Zarathustra’s teaching that a summary of his doctrines would miss?",
    edition: "Prefer Walter Kaufmann’s translation. Thomas Common’s free version has older diction and different discourse titles, including ‘Self-Surpassing’ for ‘On Self-Overcoming.’ Use the part and discourse as well as the title to locate a reading.",
    links: [{ label: "Read Thus Spake Zarathustra", translator: "Thomas Common", url: "https://www.gutenberg.org/files/1998/1998-h/1998-h.htm" }],
  },
  "beyond-good-and-evil": {
    dates: "1886",
    overview: "Nietzsche turns suspicion on philosophy’s assumptions, including its investment in truth, its accounts of agency, and its moral ambitions. The book moves from the prejudices of philosophers to questions of religion, scholarship, Europe, and nobility. Its accounts of rank and domination are part of the argument and require direct scrutiny.",
    start: ["Read the Preface and §§1–6 to identify the challenge to philosophy’s self-understanding.", "Compare §§13, 22, and 36: ask when will to power functions as a claim, an interpretation, or a hypothesis.", "Read §§257–260 together, including their social and political implications, before using the master/slave distinction."],
    question: "How can Nietzsche criticize the moral commitments of other philosophers while defending his own evaluations?",
    edition: "Prefer Walter Kaufmann’s translation. Helen Zimmern’s complete older version is freely available. Section numbers remain the clearest way to compare editions.",
    links: [{ label: "Read Beyond Good and Evil", translator: "Helen Zimmern", url: "https://www.gutenberg.org/files/4363/4363-h/4363-h.htm" }],
  },
  "genealogy-of-morals": {
    dates: "1887",
    overview: "Three linked investigations challenge the apparent innocence of moral values. The First Essay examines competing modes of valuation; the Second investigates promising, punishment, guilt, and bad conscience; the Third asks why the ascetic ideal can give suffering a meaning. The Preface makes their evaluative purpose explicit: origins matter because the value of values is in question.",
    start: ["Read the complete Preface §§1–8, then the complete First Essay rather than isolating §10.", "In the Second Essay, distinguish debt (§§4–5), punishment (§§12–15), internalization (§§16–18), and guilt before the gods (§§19–22).", "Read the Third Essay through §28. Its final sections connect science, the will to truth, and the need for a meaning for suffering."],
    question: "What would a genealogy have to establish before its account of the origin of a value became a persuasive criticism of that value?",
    edition: "Prefer Walter Kaufmann and R. J. Hollingdale’s translation. The work is also titled On the Genealogy of Morality. The free edition’s primary text is translated by Horace B. Samuel; its additional ‘Peoples and Countries’ fragment is a separate text.",
    links: [{ label: "Read The Genealogy of Morals", translator: "Horace B. Samuel", url: "https://www.gutenberg.org/files/52319/52319-h/52319-h.htm" }],
  },
  "twilight-of-the-idols": {
    dates: "Written in 1888; published in 1889",
    overview: "Compressed polemics revisit Nietzsche’s objections to philosophical ‘true worlds,’ moral hostility to the passions, and explanations that misidentify causes. The hammer tests established ideals as well as striking them. Because the prose is unusually condensed, a familiar maxim should be returned to its section and compared with a fuller argument elsewhere.",
    start: ["Read the Preface and ‘How the “True World” Finally Became a Fable.’", "Read ‘Morality as Anti-Nature’ alongside ‘The Four Great Errors.’", "Read ‘What I Owe to the Ancients’ §5 and compare its Dionysian affirmation with The Birth of Tragedy and the 1886 self-criticism."],
    question: "What standard lets Nietzsche distinguish the transformation of a passion from its destructive suppression?",
    edition: "Walter Kaufmann’s translation appears in The Portable Nietzsche. The free Anthony M. Ludovici volume also contains The Antichrist and notebook material; use its contents to keep those texts separate.",
    links: [{ label: "Read Twilight of the Idols", translator: "Anthony M. Ludovici", url: "https://www.gutenberg.org/cache/epub/52263/pg52263-images.html" }],
  },
  antichrist: {
    dates: "Written in 1888; first published in 1895",
    overview: "Nietzsche’s late polemic evaluates Christianity through questions of power, pity, priesthood, and the interpretation of life. Its treatment of Jesus, the church, and Christian morality must be distinguished rather than compressed into a single target. Its attacks on equality and its rhetoric of exclusion require criticism alongside an account of what the text is trying to explain.",
    start: ["Read the Preface and §§1–7 to identify the evaluative standard being proposed.", "Read §§24–27 on priestly valuation and compare Genealogy I §§6–8.", "Compare §§29–35 on Jesus with §§39–43 on the formation and consequences of Christianity."],
    question: "Which of Nietzsche’s claims depend on historical evidence, and which depend on accepting his evaluative standard?",
    edition: "Walter Kaufmann’s translation is included in The Portable Nietzsche. H. L. Mencken’s older translation is freely available; its introduction is the translator’s commentary, distinct from Nietzsche’s text.",
    links: [{ label: "Read The Antichrist", translator: "H. L. Mencken", url: "https://www.gutenberg.org/ebooks/19322" }],
  },
  "ecce-homo": {
    dates: "Written in 1888; first published in 1908",
    overview: "Nietzsche interprets his life and books through autobiography, provocation, self-staging, and retrospective argument. It is valuable evidence of how he wanted his work to be understood in 1888, but that perspective should be compared with the earlier books themselves. Its titles and dramatic claims make tone part of the reading problem.",
    start: ["Read the Preface before deciding how literally to take the book’s self-presentation.", "Read ‘Why I Am So Wise’ §6 and ‘Why I Am So Clever’ §§9–10 on ressentiment and love of fate.", "Read Nietzsche’s account of a book you have already studied, then compare the original argument with this retrospective interpretation."],
    question: "When does Nietzsche’s account illuminate an earlier book, and when might it reorganize that book to serve a later purpose?",
    edition: "Prefer Walter Kaufmann’s translation. In the free volume Anthony M. Ludovici translates the autobiography; several translators contribute to the accompanying poetry. Keep those supplements distinct from Ecce Homo.",
    links: [{ label: "Read Ecce Homo", translator: "Anthony M. Ludovici", url: "https://www.gutenberg.org/files/52190/52190-h/52190-h.htm" }],
  },
};
